baseURL = 'https://looechao.com'
languageCode = 'zh-cn'
theme = "lucid"
pygmentsCodeFences = true
pygmentsUseClasses = true
buildFuture = true
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]


[pagination]
pagerSize = 15


[params]
author = "looechao"
description = "looechao's blog."
favicon = "/images/favicon.png"


[params.profile]
name = "Looe"
bio = "looechao"
avatar = "/images/profile.png"
favicon = "/images/favicon.png"


  [params.social]
    email = "lu.chao.personal@gmail.com"
    github = "https://www.github.com/looechao"
    rss = ""

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/post'
weight = 20

[[menus.main]]
name = 'Archive'
pageRef = '/post'
weight = 25

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30


[frontmatter]
## lastmod = ["lastmod", ":fileModTime", ":default"]


[params.gitalk]
    enable = true
    clientID = "4fad9f9325f73f2c2891"
    clientSecret = "109ed02ced3608e776a41f87de4ef9986f5b5fd6"
    repo = "hugo-comments"
    owner = "looechao"
    admin = "looechao"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 50
    pagerDirection = "last"
    createIssueManually = false
    distractionFreeMode = false
