baseURL = 'https://looechao.com'
buildFuture = true
languageCode = 'zh-cn'
pygmentsCodeFences = true
pygmentsUseClasses = true
title = 'looechao'
theme = "lucid"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[pagination]
pagerSize = 15

[params]
author = "looechao"
description = "looechao's blog."
favicon = "/images/favicon.png"

[params.profile]
avatar = "/images/profile.png"
bio = "looechao"
favicon = "/images/favicon.png"
name = "Looe"

[params.social]
email = "lu.chao.personal@gmail.com"
github = "https://www.github.com/looechao"
rss = ""

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/post'
weight = 20

[[menus.main]]
name = 'Archive'
pageRef = '/post'
weight = 25

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[frontmatter]
## lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
[services.googleAnalytics]
id = 'G-9W970VLJ6X'

[params.gitalk]
admin = "looechao"
clientID = "4fad9f9325f73f2c2891"
clientSecret = "109ed02ced3608e776a41f87de4ef9986f5b5fd6"
createIssueManually = false
distractionFreeMode = false
enable = true
id = "location.pathname"
labels = "gitalk"
owner = "looechao"
pagerDirection = "last"
perPage = 50
repo = "hugo-comments"
