baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'looechao'

[pagination]
pagerSize = 15

# 网站参数
[params]
  # 基本信息
  author = "looechao"
  description = "looechao's blog."
  favicon = "/images/favicon.png"  
  
  # 个人资料配置
  [params.profile]
    name = "Looe"
    bio = "looechao"
    avatar = "/images/avatar.png"  # 头像图片路径，相对于 static 目录
  
  # 社交媒体链接
  [params.social]
    email = ""
    github = ""
    rss = ""

  # Giscus 评论配置
  [params.giscus]
    enable = true
    repo = "your-github-giscus-repo"
    repo_id = "repoid"
    category = "category"
    category_id = "categoryid"
    mapping = "pathname"
    reactions_enabled = true
    emit_metadata = false
    theme = "light"
    lang = "en"


[menus]
  [[menus.main]]
    pageRef = '/'
    weight = 10

  [[menus.main]]
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    pageRef = '/posts'
    weight = 25

  [[menus.main]]
    pageRef = '/tags'
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = 'github'
    tabWidth = 4

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
